name: Metrics
on:
  # Schedule updates (once every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: lemongoreng
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kuala_Lumpur
          
          # This makes it look cool (Isometric Calendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Top Languages
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
