name: Metrics
on:
  # Update daily
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Your Info
          user: lemongoreng
          template: classic
          config_timezone: Asia/Kuala_Lumpur
          
          # 1. Base Stats (Commits, PRs, etc.)
          base: header, activity, community, repositories
          
          # 2. Most Used Languages
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 8
          
          # 3. Activity (The 3D Calendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
